=== Cubafehis0/DialogLogic/Assets/GameConfig/GameTestConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="JaspersGameConfigGrammar"
xmlns="JaspersGameConfigGrammar"
elementFormDefault="qualified">
<xs:element name="pass">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="InkStory"/>
            <xs:element name="player">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="personality"/>
                        <xs:element name="maxCardNum" type="xs:integer"/>
                        <xs:element name="drawCardNum" type="xs:integer"/>
                        <xs:element name="basePressure" type="xs:integer"/>
                        <xs:element name="maxPressure" type="xs:integer"/> 
                        <xs:element name="health" type="xs:integer"/>
                        <xs:element name="energy" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="enemy">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="personality"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cardDeck">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="card">
                            <xs:complexType>
                                <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                    <xs:element name="name" type="xs:string"/>
                                    <xs:element name="num" type="xs:integer" default="1"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="personality">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="logic" type="xs:integer"/>
            <xs:element name="moral" type="xs:integer"/>
            <xs:element name="roundabout" type="xs:integer"/>
            <xs:element name="inner" type="xs:integer"/>
            <xs:element name="outside" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Cubafehis0/DialogLogic/Assets/GameConfig/EG1-1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pass xmlns="JaspersGameConfigGrammar"
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="JaspersGameConfigGrammar GameTestConfig.xsd">
<InkStory>EG1-1</InkStory>
    <player>
        <personality>
            <logic>0</logic>
            <moral>0</moral>
            <roundabout>0</roundabout>
            <inner>0</inner>
            <outside>0</outside>
        </personality>
        <maxCardNum>10</maxCardNum>
        <drawCardNum>3</drawCardNum>
        <basePressure>0</basePressure>
        <maxPressure>100</maxPressure>
        <health>80</health>
        <energy>4</energy>
    </player>
    <enemy>
        <personality>
            <logic>0</logic>
            <moral>0</moral>
            <roundabout>0</roundabout>
            <inner>0</inner>
            <outside>0</outside>
        </personality>
    </enemy>
    <cardDeck>
        <card>
            <name>xsa</name>
            <num>2</num>
        </card>
    </cardDeck>
</pass>
